"""Qubit-cavity conditional and interaction gates for cqed_sim.

All gates in this module act on a composite qubit ⊗ cavity Hilbert space.

Tensor-ordering convention (matches the rest of cqed_sim)
----------------------------------------------------------
    **Qubit first, cavity second.**

    A joint ket is ``qt.tensor(qubit_ket, cavity_ket)``, and the composite
    dimension is ``qubit_dim * cavity_dim``.  Concretely for the default
    ``qubit_dim = 2``:

    - Index ``0 … cavity_dim-1``:  ``|g, 0⟩ … |g, N-1⟩``
    - Index ``cavity_dim … 2*cavity_dim-1``: ``|e, 0⟩ … |e, N-1⟩``

Basis convention
----------------
    ``|g⟩ = basis(2, 0)``,  ``|e⟩ = basis(2, 1)``.

Dispersive-phase convention
---------------------------
    Default (``convention="n_e"``):

    .. math::

        H_\\chi = \\chi\\, a^\\dagger a\\, |e\\rangle\\langle e|

    Alternative (``convention="z"``):

    .. math::

        H_\\chi = \\frac{\\chi}{2}\\, a^\\dagger a\\, Z

    With the same sign of ``χ``, the two conventions differ by a branch-
    dependent global phase (a photon-number-dependent phase on both |g⟩ and
    |e⟩ branches), but produce the same *relative* dispersive phase between
    the two qubit branches.  The ``"n_e"`` convention is the default because
    it matches the Hamiltonian used in ``UniversalCQEDModel``.

Units
-----
    Angles in radians; coupling ``χ`` and ``g`` in rad/s; time in seconds.
"""

from __future__ import annotations

from typing import Sequence

import numpy as np
import qutip as qt

from cqed_sim.core.ideal_gates import qubit_rotation_xy
from cqed_sim.gates.bosonic import displacement, parity, snap


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _qubit_projector(qubit_dim: int, level: int) -> qt.Qobj:
    ket = qt.basis(int(qubit_dim), int(level))
    return ket * ket.dag()


def _cavity_number_op(cavity_dim: int) -> qt.Qobj:
    a = qt.destroy(int(cavity_dim))
    return a.dag() * a


# ---------------------------------------------------------------------------
# 4.1  Dispersive conditional phase evolution
# ---------------------------------------------------------------------------

def dispersive_phase(
    chi: float,
    time: float,
    cavity_dim: int,
    qubit_dim: int = 2,
    convention: str = "n_e",
) -> qt.Qobj:
    """Dispersive-shift unitary generated by the cross-Kerr-like Hamiltonian.

    Parameters
    ----------
    chi:
        Dispersive coupling in rad/s.  For a transmon-storage system, ``χ``
        is typically negative (tens of kHz to a few MHz range).
    time:
        Evolution time in seconds.
    cavity_dim:
        Fock-space truncation dimension of the cavity.
    qubit_dim:
        Dimension of the qubit / transmon Hilbert space (default 2).
    convention:
        ``"n_e"`` (default) or ``"z"``.

        * ``"n_e"``: generates from ``H = χ n̂_cav |e⟩⟨e|``

          .. math::

              U = \\exp(-it H) =
              |g\\rangle\\langle g| \\otimes I +
              |e\\rangle\\langle e| \\otimes \\exp(-i\\chi t\\,\\hat n)

        * ``"z"``: generates from ``H = (χ/2) n̂_cav Z``

          .. math::

              U = \\exp(-it H) =
              \\exp(-i\\chi t/2\\, \\hat n) \\otimes |g\\rangle\\langle g| +
              \\exp(+i\\chi t/2\\, \\hat n) \\otimes |e\\rangle\\langle e|

    Returns
    -------
    qt.Qobj
        A ``(qubit_dim * cavity_dim) × (qubit_dim * cavity_dim)`` unitary.
    """
    chi = float(chi)
    time = float(time)
    cav_dim = int(cavity_dim)
    q_dim = int(qubit_dim)

    n_vals = np.arange(cav_dim, dtype=float)

    if convention == "n_e":
        # U = |g><g| ⊗ I_cav + sum_{k=1..q_dim-1} ... (generalised)
        # For qubit_dim=2: |g><g| ⊗ I + |e><e| ⊗ exp(-iχt n̂)
        # Generalised: only level 1 (|e>) picks up the phase
        result = qt.tensor(_qubit_projector(q_dim, 0), qt.qeye(cav_dim))
        phase_e = np.exp(-1j * chi * time * n_vals)
        diag_e = qt.Qobj(np.diag(phase_e), dims=[[cav_dim], [cav_dim]])
        for k in range(1, q_dim):
            result = result + qt.tensor(_qubit_projector(q_dim, k), diag_e)
        return result

    elif convention == "z":
        if q_dim != 2:
            raise ValueError("convention='z' only supports qubit_dim=2.")
        # H = (χ/2) n̂ Z;  Z = |g><g| - |e><e|
        # U = exp(-iχt/2 n̂) |g><g| + exp(+iχt/2 n̂) |e><e|
        phase_g = np.exp(-1j * chi * time / 2.0 * n_vals)
        phase_e = np.exp(+1j * chi * time / 2.0 * n_vals)
        diag_g = qt.Qobj(np.diag(phase_g), dims=[[cav_dim], [cav_dim]])
        diag_e = qt.Qobj(np.diag(phase_e), dims=[[cav_dim], [cav_dim]])
        return (
            qt.tensor(_qubit_projector(2, 0), diag_g)
            + qt.tensor(_qubit_projector(2, 1), diag_e)
        )
    else:
        raise ValueError(
            f"Unknown convention '{convention}'.  Choose 'n_e' or 'z'."
        )


# ---------------------------------------------------------------------------
# 4.2  Conditional cavity rotation
# ---------------------------------------------------------------------------

def conditional_rotation(
    theta: float,
    cavity_dim: int,
    qubit_dim: int = 2,
    control_state: str = "e",
) -> qt.Qobj:
    """Conditional oscillator-rotation gate.

    .. math::

        U = |g\\rangle\\langle g| \\otimes I
          + |e\\rangle\\langle e| \\otimes \\exp(-i\\theta\\,\\hat n)

    when ``control_state="e"``, or with the roles of g and e swapped when
    ``control_state="g"``.

    Parameters
    ----------
    theta:
        Rotation angle in radians applied to the cavity.
    cavity_dim:
        Fock-space truncation dimension.
    qubit_dim:
        Qubit Hilbert-space dimension (default 2).
    control_state:
        Which qubit state triggers the cavity rotation.  ``"e"`` means the
        standard dispersive-readout convention (cavity rotates when qubit
        is excited); ``"g"`` flips the control.

    Returns
    -------
    qt.Qobj
        A ``(qubit_dim * cavity_dim) × (qubit_dim * cavity_dim)`` unitary.
    """
    q_dim = int(qubit_dim)
    cav_dim = int(cavity_dim)
    if q_dim < 2:
        raise ValueError("qubit_dim must be at least 2.")

    n_vals = np.arange(cav_dim, dtype=float)
    rot_phases = np.exp(-1j * float(theta) * n_vals)
    rot_op = qt.Qobj(np.diag(rot_phases), dims=[[cav_dim], [cav_dim]])

    if control_state == "e":
        ctrl_idx, pass_idx = 1, 0
    elif control_state == "g":
        ctrl_idx, pass_idx = 0, 1
    else:
        raise ValueError("control_state must be 'e' or 'g'.")

    # For qubit_dim == 2 this is the standard form; for higher dims all
    # levels except ctrl_idx pass through with identity.
    result = qt.tensor(_qubit_projector(q_dim, ctrl_idx), rot_op)
    for k in range(q_dim):
        if k != ctrl_idx:
            result = result + qt.tensor(_qubit_projector(q_dim, k), qt.qeye(cav_dim))
    return result


# ---------------------------------------------------------------------------
# 4.3  Conditional displacement
# ---------------------------------------------------------------------------

def conditional_displacement(
    alpha: complex | None = None,
    *,
    alpha_g: complex | None = None,
    alpha_e: complex | None = None,
    cavity_dim: int,
    qubit_dim: int = 2,
) -> qt.Qobj:
    """Conditional displacement gate.

    Supports two call signatures:

    **Symmetric form** (most common in experiments):

    .. math::

        CD(\\alpha) = |g\\rangle\\langle g| \\otimes D(+\\alpha)
                    + |e\\rangle\\langle e| \\otimes D(-\\alpha)

    Invoked by passing ``alpha`` only.

    **General form**:

    .. math::

        CD(\\alpha_g, \\alpha_e) =
            |g\\rangle\\langle g| \\otimes D(\\alpha_g)
          + |e\\rangle\\langle e| \\otimes D(\\alpha_e)

    Invoked by passing ``alpha_g`` and ``alpha_e`` (and leaving ``alpha``
    unset).

    Parameters
    ----------
    alpha:
        Displacement amplitude for the symmetric form.
    alpha_g:
        Displacement applied to the cavity when the qubit is in ``|g⟩``.
    alpha_e:
        Displacement applied to the cavity when the qubit is in ``|e⟩``.
    cavity_dim:
        Fock-space truncation dimension.
    qubit_dim:
        Qubit dimension (default 2).  Only ``qubit_dim=2`` is supported for
        the conditional form.

    Returns
    -------
    qt.Qobj
        A ``(2 * cavity_dim) × (2 * cavity_dim)`` unitary.
    """
    q_dim = int(qubit_dim)
    cav_dim = int(cavity_dim)
    if q_dim != 2:
        raise ValueError("conditional_displacement only supports qubit_dim=2.")

    if alpha is not None:
        if alpha_g is not None or alpha_e is not None:
            raise ValueError(
                "Provide either 'alpha' alone (symmetric) or 'alpha_g' and "
                "'alpha_e' together (general), not both."
            )
        ag = complex(alpha)
        ae = -complex(alpha)
    elif alpha_g is not None and alpha_e is not None:
        ag = complex(alpha_g)
        ae = complex(alpha_e)
    else:
        raise ValueError(
            "Provide 'alpha' for the symmetric form, or both 'alpha_g' and "
            "'alpha_e' for the general form."
        )

    D_g = displacement(ag, cav_dim)
    D_e = displacement(ae, cav_dim)
    return (
        qt.tensor(_qubit_projector(2, 0), D_g)
        + qt.tensor(_qubit_projector(2, 1), D_e)
    )


# ---------------------------------------------------------------------------
# 4.4  Controlled parity
# ---------------------------------------------------------------------------

def controlled_parity(cavity_dim: int, qubit_dim: int = 2) -> qt.Qobj:
    """Controlled-parity gate: applies photon parity when qubit is in ``|e⟩``.

    .. math::

        U = |g\\rangle\\langle g| \\otimes I
          + |e\\rangle\\langle e| \\otimes \\Pi

    where ``Π = exp(i π a†a)`` maps ``|n⟩ → (-1)^n |n⟩``.

    Parameters
    ----------
    cavity_dim:
        Fock-space truncation dimension.
    qubit_dim:
        Qubit dimension (default 2).

    Returns
    -------
    qt.Qobj
        A ``(qubit_dim * cavity_dim) × (qubit_dim * cavity_dim)`` unitary.
    """
    q_dim = int(qubit_dim)
    cav_dim = int(cavity_dim)
    P = parity(cav_dim)
    result = qt.tensor(_qubit_projector(q_dim, 0), qt.qeye(cav_dim))
    for k in range(1, q_dim):
        result = result + qt.tensor(_qubit_projector(q_dim, k), P)
    return result


# ---------------------------------------------------------------------------
# 4.5  Controlled SNAP
# ---------------------------------------------------------------------------

def controlled_snap(
    phases: dict[int, float] | Sequence[float] | np.ndarray,
    cavity_dim: int,
    qubit_dim: int = 2,
) -> qt.Qobj:
    """Controlled-SNAP gate: applies SNAP when qubit is in ``|e⟩``.

    .. math::

        U = |g\\rangle\\langle g| \\otimes I
          + |e\\rangle\\langle e| \\otimes S(\\{\\phi_n\\})

    Parameters
    ----------
    phases:
        SNAP phases, in the same format as :func:`~cqed_sim.gates.bosonic.snap`:
        a dict ``{n: phase}`` or a dense list / array.
    cavity_dim:
        Fock-space truncation dimension.
    qubit_dim:
        Qubit dimension (default 2).

    Returns
    -------
    qt.Qobj
        A ``(qubit_dim * cavity_dim) × (qubit_dim * cavity_dim)`` unitary.
    """
    q_dim = int(qubit_dim)
    cav_dim = int(cavity_dim)
    S = snap(phases, cav_dim)
    result = qt.tensor(_qubit_projector(q_dim, 0), qt.qeye(cav_dim))
    for k in range(1, q_dim):
        result = result + qt.tensor(_qubit_projector(q_dim, k), S)
    return result


# ---------------------------------------------------------------------------
# 4.6  Number-selective qubit rotation (SQR-like)
# ---------------------------------------------------------------------------

def sqr(
    theta: float,
    phi: float,
    n: int,
    cavity_dim: int,
    qubit_dim: int = 2,
) -> qt.Qobj:
    """Number-selective qubit rotation at Fock level ``n`` (single-tone SQR).

    .. math::

        U = |n\\rangle\\langle n| \\otimes R_\\phi(\\theta)
          + \\sum_{m \\neq n} |m\\rangle\\langle m| \\otimes I

    Only the qubit subspace corresponding to Fock level ``n`` is rotated;
    all other cavity levels act as identity on the qubit.

    Parameters
    ----------
    theta:
        Qubit rotation angle in radians.
    phi:
        Qubit drive phase in radians.
    n:
        Target Fock level (0-based).
    cavity_dim:
        Fock-space truncation dimension.
    qubit_dim:
        Qubit dimension (default 2).

    Returns
    -------
    qt.Qobj
        A ``(qubit_dim * cavity_dim) × (qubit_dim * cavity_dim)`` unitary.

    Notes
    -----
    Tensor ordering is **qubit first, cavity second**, consistent with all
    other gates in this module and with the repository-wide convention
    ``qt.tensor(qubit, cavity)``.
    """
    cav_dim = int(cavity_dim)
    q_dim = int(qubit_dim)
    n = int(n)
    if not (0 <= n < cav_dim):
        raise ValueError(f"Fock level n={n} must be in [0, {cav_dim - 1}].")

    rot = qubit_rotation_xy(float(theta), float(phi))
    identity_q = qt.qeye(q_dim)
    pn = qt.basis(cav_dim, n) * qt.basis(cav_dim, n).dag()

    result = qt.tensor(rot, pn)
    for m in range(cav_dim):
        if m != n:
            result = result + qt.tensor(
                identity_q,
                qt.basis(cav_dim, m) * qt.basis(cav_dim, m).dag(),
            )
    return result


def multi_sqr(
    theta_by_n: dict[int, float] | Sequence[float] | np.ndarray,
    phi_by_n: dict[int, float] | Sequence[float] | np.ndarray,
    cavity_dim: int,
    qubit_dim: int = 2,
) -> qt.Qobj:
    """Generalised multi-tone SQR gate.

    .. math::

        U = \\sum_n |n\\rangle\\langle n| \\otimes R_{\\phi_n}(\\theta_n)

    Each Fock level ``n`` can receive a different qubit rotation.

    Parameters
    ----------
    theta_by_n:
        Rotation angles per Fock level.  One of:

        * **dict** ``{n: theta}``: sparse; unspecified levels get ``theta=0``
          (identity rotation).
        * **array / list** of length ``cavity_dim``: dense; ``theta_by_n[n]``
          is the angle for level ``n``.

    phi_by_n:
        Drive phases per Fock level, same format as ``theta_by_n``.
    cavity_dim:
        Fock-space truncation dimension.
    qubit_dim:
        Qubit dimension (default 2).

    Returns
    -------
    qt.Qobj
        A ``(qubit_dim * cavity_dim) × (qubit_dim * cavity_dim)`` unitary.

    Notes
    -----
    Tensor ordering is **qubit first, cavity second**, consistent with all
    other gates in this module and with the repository-wide convention
    ``qt.tensor(qubit, cavity)``.
    """
    cav_dim = int(cavity_dim)
    q_dim = int(qubit_dim)

    # Build dense arrays
    thetas = np.zeros(cav_dim, dtype=float)
    phis = np.zeros(cav_dim, dtype=float)

    if isinstance(theta_by_n, dict):
        for n, t in theta_by_n.items():
            thetas[int(n)] = float(t)
    else:
        arr = np.asarray(theta_by_n, dtype=float).reshape(-1)
        if arr.size != cav_dim:
            raise ValueError(
                f"Dense theta_by_n length {arr.size} must equal cavity_dim={cav_dim}."
            )
        thetas[:] = arr

    if isinstance(phi_by_n, dict):
        for n, p in phi_by_n.items():
            phis[int(n)] = float(p)
    else:
        arr = np.asarray(phi_by_n, dtype=float).reshape(-1)
        if arr.size != cav_dim:
            raise ValueError(
                f"Dense phi_by_n length {arr.size} must equal cavity_dim={cav_dim}."
            )
        phis[:] = arr

    result = 0 * qt.tensor(qt.qeye(q_dim), qt.qeye(cav_dim))
    for n in range(cav_dim):
        pn = qt.basis(cav_dim, n) * qt.basis(cav_dim, n).dag()
        rot = qubit_rotation_xy(thetas[n], phis[n])
        result = result + qt.tensor(rot, pn)
    return result


# ---------------------------------------------------------------------------
# 5.1  Jaynes–Cummings exchange gate
# ---------------------------------------------------------------------------

def jaynes_cummings(
    g: float,
    time: float,
    cavity_dim: int,
    qubit_dim: int = 2,
) -> qt.Qobj:
    """Jaynes–Cummings exchange unitary.

    Generates from the rotating-wave Hamiltonian (qubit first, cavity second):

    .. math::

        H_{\\text{JC}} = g\\left(\\sigma_+ \\otimes a + \\sigma_- \\otimes a^\\dagger\\right)

    .. math::

        U_{\\text{JC}}(t) = \\exp(-it H_{\\text{JC}})

    Parameters
    ----------
    g:
        Exchange coupling in rad/s.
    time:
        Evolution time in seconds.
    cavity_dim:
        Fock-space truncation dimension.
    qubit_dim:
        Qubit dimension (default 2).  For ``qubit_dim=2`` uses the standard
        ``σ+ = |e⟩⟨g|`` ladder operator; for higher dims uses ``|1⟩⟨0|``.

    Returns
    -------
    qt.Qobj
        A ``(qubit_dim * cavity_dim) × (qubit_dim * cavity_dim)`` unitary.

    Notes
    -----
    The coupling ``g`` here is the vacuum Rabi rate (not ``2g``).
    """
    q_dim = int(qubit_dim)
    cav_dim = int(cavity_dim)

    # σ+ = |e><g| = |1><0| in the {g,e} basis
    sigma_plus = qt.basis(q_dim, 1) * qt.basis(q_dim, 0).dag()
    sigma_minus = sigma_plus.dag()
    a = qt.destroy(cav_dim)

    h = float(g) * (
        qt.tensor(sigma_plus, a) + qt.tensor(sigma_minus, a.dag())
    )
    return (-1j * float(time) * h).expm()


# ---------------------------------------------------------------------------
# 5.2  Blue-sideband exchange gate
# ---------------------------------------------------------------------------

def blue_sideband(
    g: float,
    time: float,
    cavity_dim: int,
    qubit_dim: int = 2,
) -> qt.Qobj:
    """Blue-sideband (two-photon) exchange unitary.

    Generates from:

    .. math::

        H_{\\text{blue}} = g\\left(\\sigma_+ \\otimes a^\\dagger + \\sigma_- \\otimes a\\right)

    .. math::

        U_{\\text{blue}}(t) = \\exp(-it H_{\\text{blue}})

    Parameters
    ----------
    g:
        Exchange coupling in rad/s.
    time:
        Evolution time in seconds.
    cavity_dim:
        Fock-space truncation dimension.
    qubit_dim:
        Qubit dimension (default 2).

    Returns
    -------
    qt.Qobj
        A ``(qubit_dim * cavity_dim) × (qubit_dim * cavity_dim)`` unitary.
    """
    q_dim = int(qubit_dim)
    cav_dim = int(cavity_dim)

    sigma_plus = qt.basis(q_dim, 1) * qt.basis(q_dim, 0).dag()
    sigma_minus = sigma_plus.dag()
    a = qt.destroy(cav_dim)

    h = float(g) * (
        qt.tensor(sigma_plus, a.dag()) + qt.tensor(sigma_minus, a)
    )
    return (-1j * float(time) * h).expm()


# ---------------------------------------------------------------------------
# 5.3  Beam-splitter (mode-mode exchange) – ergonomic alias
# ---------------------------------------------------------------------------

def beam_splitter(g: float, time: float, dim_a: int, dim_b: int) -> qt.Qobj:
    """Two-mode beam-splitter unitary.

    Generates from:

    .. math::

        H_{\\text{BS}} = g\\left(a^\\dagger b + a b^\\dagger\\right)

    .. math::

        U_{\\text{BS}}(t) = \\exp(-it H_{\\text{BS}})

    Parameters
    ----------
    g:
        Exchange coupling in rad/s.
    time:
        Evolution time in seconds.
    dim_a:
        Fock-space truncation of mode a.
    dim_b:
        Fock-space truncation of mode b.

    Returns
    -------
    qt.Qobj
        A ``(dim_a * dim_b) × (dim_a * dim_b)`` unitary.

    Notes
    -----
    Equivalent to :func:`~cqed_sim.core.ideal_gates.beamsplitter_unitary`
    with ``theta = g * time``.
    """
    from cqed_sim.core.ideal_gates import beamsplitter_unitary
    return beamsplitter_unitary(int(dim_a), int(dim_b), float(g) * float(time))


__all__ = [
    "dispersive_phase",
    "conditional_rotation",
    "conditional_displacement",
    "controlled_parity",
    "controlled_snap",
    "sqr",
    "multi_sqr",
    "jaynes_cummings",
    "blue_sideband",
    "beam_splitter",
]
