"""Single-qubit gate library for cqed_sim.

All functions return QuTiP ``qt.Qobj`` unitaries acting on a 2-dimensional
qubit Hilbert space spanned by ``{|g⟩ = basis(2,0), |e⟩ = basis(2,1)}``.

Convention summary
------------------
- Angles are in radians.
- Rotations follow the right-hand-rule: ``R_n(θ) = exp(-i θ/2 n̂·σ)``.
- The equatorial rotation is
  ``R_φ(θ) = exp[-i θ/2 (cos φ X + sin φ Y)]``,
  which is exactly ``qubit_rotation_xy(theta, phi)`` from ``core.ideal_gates``.
- Named Clifford / T gates are exact ideal matrices (not Hamiltonian-generated).
"""

from __future__ import annotations

import numpy as np
import qutip as qt

from cqed_sim.core.ideal_gates import qubit_rotation_axis, qubit_rotation_xy


# ---------------------------------------------------------------------------
# Parameterised rotations (thin wrappers around existing primitives)
# ---------------------------------------------------------------------------

def rx(theta: float) -> qt.Qobj:
    """Rotation about the X axis: ``exp(-i θ/2 X)``."""
    return qubit_rotation_axis(float(theta), "x")


def ry(theta: float) -> qt.Qobj:
    """Rotation about the Y axis: ``exp(-i θ/2 Y)``."""
    return qubit_rotation_axis(float(theta), "y")


def rz(theta: float) -> qt.Qobj:
    """Rotation about the Z axis: ``exp(-i θ/2 Z)``."""
    return qubit_rotation_axis(float(theta), "z")


def rphi(theta: float, phi: float) -> qt.Qobj:
    """Equatorial rotation: ``exp[-i θ/2 (cos φ X + sin φ Y)]``.

    Parameters
    ----------
    theta:
        Rotation angle in radians.
    phi:
        Azimuthal drive phase in radians, measured from the X axis toward Y.

    Notes
    -----
    At ``phi=0`` this reduces to ``rx(theta)``; at ``phi=π/2`` it reduces to
    ``ry(theta)``.  This is the most general single-axis equatorial rotation
    and is the form generated by an on-resonance drive in the rotating frame.
    """
    return qubit_rotation_xy(float(theta), float(phi))


# ---------------------------------------------------------------------------
# Named single-qubit gates
# ---------------------------------------------------------------------------

def identity_gate() -> qt.Qobj:
    """2×2 identity gate."""
    return qt.qeye(2)


def x_gate() -> qt.Qobj:
    """Pauli-X gate (NOT gate).

    Exact matrix: ``[[0, 1], [1, 0]]``.
    Equivalent to ``rx(π)`` up to global phase.
    """
    return qt.sigmax()


def y_gate() -> qt.Qobj:
    """Pauli-Y gate.

    Exact matrix: ``[[0, -i], [i, 0]]``.
    Equivalent to ``ry(π)`` up to global phase.
    """
    return qt.sigmay()


def z_gate() -> qt.Qobj:
    """Pauli-Z gate.

    Exact matrix: ``diag(1, -1)`` in the ``{|g⟩, |e⟩}`` basis.
    Equivalent to ``rz(π)`` up to global phase.
    """
    return qt.sigmaz()


def h_gate() -> qt.Qobj:
    """Hadamard gate.

    Exact matrix: ``(X + Z) / √2``.
    Maps ``|g⟩ → |+x⟩`` and ``|e⟩ → |-x⟩``.
    """
    return (qt.sigmax() + qt.sigmaz()) / np.sqrt(2.0)


def s_gate() -> qt.Qobj:
    """Phase gate S = ``diag(1, i)``.

    Equivalent to ``rz(-π/2)`` up to global phase.  Satisfies ``S² = Z``.
    """
    return qt.Qobj(
        np.diag([1.0, 1j]).astype(np.complex128),
        dims=[[2], [2]],
    )


def s_dag_gate() -> qt.Qobj:
    """Conjugate-transpose of the S gate: ``diag(1, -i)``.

    Satisfies ``S† S = I``.
    """
    return qt.Qobj(
        np.diag([1.0, -1j]).astype(np.complex128),
        dims=[[2], [2]],
    )


def t_gate() -> qt.Qobj:
    """T gate = ``diag(1, exp(i π/4))``.

    Satisfies ``T² = S``, ``T⁴ = Z`` (up to global phase).
    """
    return qt.Qobj(
        np.diag([1.0, np.exp(1j * np.pi / 4.0)]).astype(np.complex128),
        dims=[[2], [2]],
    )


def t_dag_gate() -> qt.Qobj:
    """Conjugate-transpose of the T gate: ``diag(1, exp(-i π/4))``."""
    return qt.Qobj(
        np.diag([1.0, np.exp(-1j * np.pi / 4.0)]).astype(np.complex128),
        dims=[[2], [2]],
    )


__all__ = [
    "rx",
    "ry",
    "rz",
    "rphi",
    "identity_gate",
    "x_gate",
    "y_gate",
    "z_gate",
    "h_gate",
    "s_gate",
    "s_dag_gate",
    "t_gate",
    "t_dag_gate",
]
