from __future__ import annotations

import numpy as np
from scipy.linalg import expm

from ..channel import HolographicChannel
from .spin_models import PAULI_X, PAULI_Y, IsingTransferSpec


def hadamard_reference_channel(*, label: str | None = "hadamard_reference") -> HolographicChannel:
    """Ancilla-only reference channel with bond dimension one."""

    hadamard = (1.0 / np.sqrt(2.0)) * np.array([[1.0, 1.0], [1.0, -1.0]], dtype=np.complex128)
    return HolographicChannel.from_unitary(hadamard, physical_dim=2, bond_dim=1, label=label)


def partial_swap_channel(theta: float, *, label: str | None = None) -> HolographicChannel:
    """Translation-invariant qubit channel generated by an XY partial-swap interaction."""

    interaction = 0.5 * (np.kron(PAULI_X, PAULI_X) + np.kron(PAULI_Y, PAULI_Y))
    unitary = expm(-1j * float(theta) * interaction)
    return HolographicChannel.from_unitary(
        unitary,
        physical_dim=2,
        bond_dim=2,
        label="partial_swap" if label is None else label,
        metadata={"theta": float(theta), "model_family": "xy_partial_swap"},
    )


def ising_transfer_channel(
    *,
    spec: IsingTransferSpec | None = None,
    zz_coupling: float = 0.8,
    hx_physical: float = 0.3,
    hx_bond: float = 0.2,
    hz_physical: float = 0.0,
    hz_bond: float = 0.0,
    time: float = 1.0,
    label: str | None = None,
) -> HolographicChannel:
    """Spin-inspired holographic channel used in the examples and tests."""

    resolved = spec or IsingTransferSpec(
        zz_coupling=zz_coupling,
        hx_physical=hx_physical,
        hx_bond=hx_bond,
        hz_physical=hz_physical,
        hz_bond=hz_bond,
        time=time,
    )
    return HolographicChannel.from_unitary(
        resolved.unitary(),
        physical_dim=2,
        bond_dim=2,
        label="ising_transfer" if label is None else label,
        metadata={"model_family": "transverse_field_ising", "spec": resolved.__dict__.copy()},
    )
