import os

_SUPPRESS_DEPRECATION_ENV = "CQED_SIM_SUPPRESS_UNITARY_SYNTHESIS_DEPRECATION"
_previous_suppression = os.environ.get(_SUPPRESS_DEPRECATION_ENV)
os.environ[_SUPPRESS_DEPRECATION_ENV] = "1"

try:
    from cqed_sim.unitary_synthesis.backends import SimulationResult, simulate_sequence
    from cqed_sim.unitary_synthesis.config import ExecutionOptions, LeakagePenalty, MultiObjective, Normal, ParameterDistribution, SynthesisConstraints, Uniform
    from cqed_sim.unitary_synthesis.constraints import (
        SlewConstraintResult,
        TimeGridResult,
        ToneSpacingResult,
        enforce_slew_limit,
        evaluate_tone_spacing,
        piecewise_constant_samples,
        project_tone_frequencies,
        snap_times_to_grid,
    )
    from cqed_sim.unitary_synthesis import metrics
    from cqed_sim.unitary_synthesis.metrics import (
        LogicalBlockPhaseDiagnostics,
        channel_action_metrics,
        channel_average_gate_fidelity,
        channel_entanglement_fidelity,
        channel_process_fidelity,
        isometry_basis_fidelity,
        isometry_coherent_fidelity,
        isometry_random_superposition_metrics,
        isometry_retention,
        leakage_metrics,
        logical_block_phase_diagnostics,
        operator_truncation_sanity_metrics,
        projected_density_matrix,
        projector_population_metrics,
        state_population_distribution,
        subspace_unitary_fidelity,
        subspace_unitary_process_fidelity,
        truncation_sanity_metrics,
    )
    from cqed_sim.unitary_synthesis.objectives import (
        MetricSpec,
        default_metric_specs,
        metric_cost,
        metric_sense,
        normalize_metric_name,
        objective_preset_defaults,
        resolve_metric_specs,
    )
    from cqed_sim.unitary_synthesis.optim import ParetoFrontResult, SynthesisResult, TimeMapper
    from cqed_sim.unitary_synthesis.optim import UnitarySynthesizer as QuantumMapSynthesizer
    from cqed_sim.unitary_synthesis.order_search import GateOrderConfig, GateOrderOptimizer, GateOrderSearchResult
    from cqed_sim.unitary_synthesis.progress import (
        PROGRESS_SCHEMA_VERSION,
        HistoryReporter,
        JupyterLiveReporter,
        NullReporter,
        ProgressEvent,
        ProgressReporter,
        history_to_dataframe,
        plot_history,
    )
    from cqed_sim.unitary_synthesis.reporting import make_run_report
    from cqed_sim.unitary_synthesis.sequence import (
        BlueSidebandExchange,
        CavityBlockPhase,
        ConditionalDisplacement,
        Displacement,
        DriftPhaseModel,
        FreeEvolveCondPhase,
        GateSequence,
        GateTimeParam,
        JaynesCummingsExchange,
        PrimitiveGate,
        QubitRotation,
        SNAP,
        SQR,
        drift_hamiltonian_qobj,
        drift_phase_from_hamiltonian,
        drift_phase_table,
        drift_phase_unitary,
        make_gate_from_callable,
        make_gate_from_matrix,
        make_gate_from_waveform,
    )
    from cqed_sim.unitary_synthesis.subspace import Subspace
    from cqed_sim.unitary_synthesis.systems import CQEDSystemAdapter, GateRegistry, QuantumSystem, gate_registry
    from cqed_sim.unitary_synthesis.targets import (
        ObservableTarget,
        SubspaceSpec,
        TargetChannel,
        TargetIsometry,
        TargetReducedStateMapping,
        TargetStateMapping,
        TargetUnitary,
        TrajectoryCheckpoint,
        TrajectoryTarget,
        coerce_target,
        make_target,
    )
    from cqed_sim.unitary_synthesis.visualization import (
        plot_density_matrix_heatmap,
        plot_edge_population_summary,
        plot_leakage_block_heatmap,
        plot_leakage_profile,
        plot_operator_magnitude_heatmap,
        plot_output_population_bars,
        plot_projected_logical_density,
        reorder_operator_by_subspace,
    )
    from cqed_sim.unitary_synthesis.waveform_bridge import waveform_primitive_from_gate, waveform_sequence_from_gates
finally:
    if _previous_suppression is None:
        os.environ.pop(_SUPPRESS_DEPRECATION_ENV, None)
    else:
        os.environ[_SUPPRESS_DEPRECATION_ENV] = _previous_suppression

__all__ = [
    "Subspace",
    "QuantumSystem",
    "CQEDSystemAdapter",
    "SubspaceSpec",
    "make_target",
    "coerce_target",
    "TargetUnitary",
    "TargetStateMapping",
    "TargetReducedStateMapping",
    "TargetIsometry",
    "TargetChannel",
    "ObservableTarget",
    "TrajectoryCheckpoint",
    "TrajectoryTarget",
    "waveform_primitive_from_gate",
    "waveform_sequence_from_gates",
    "TimeMapper",
    "SynthesisResult",
    "ParetoFrontResult",
    "QuantumMapSynthesizer",
    "SynthesisConstraints",
    "LeakagePenalty",
    "MultiObjective",
    "ExecutionOptions",
    "Normal",
    "Uniform",
    "ParameterDistribution",
    "MetricSpec",
    "default_metric_specs",
    "metric_cost",
    "metric_sense",
    "normalize_metric_name",
    "objective_preset_defaults",
    "resolve_metric_specs",
    "TimeGridResult",
    "SlewConstraintResult",
    "ToneSpacingResult",
    "SimulationResult",
    "simulate_sequence",
    "snap_times_to_grid",
    "piecewise_constant_samples",
    "enforce_slew_limit",
    "evaluate_tone_spacing",
    "project_tone_frequencies",
    "metrics",
    "subspace_unitary_fidelity",
    "subspace_unitary_process_fidelity",
    "leakage_metrics",
    "channel_action_metrics",
    "projector_population_metrics",
    "projected_density_matrix",
    "state_population_distribution",
    "channel_process_fidelity",
    "channel_entanglement_fidelity",
    "channel_average_gate_fidelity",
    "isometry_coherent_fidelity",
    "isometry_basis_fidelity",
    "isometry_retention",
    "isometry_random_superposition_metrics",
    "LogicalBlockPhaseDiagnostics",
    "logical_block_phase_diagnostics",
    "truncation_sanity_metrics",
    "operator_truncation_sanity_metrics",
    "reorder_operator_by_subspace",
    "plot_operator_magnitude_heatmap",
    "plot_leakage_block_heatmap",
    "plot_output_population_bars",
    "plot_density_matrix_heatmap",
    "plot_projected_logical_density",
    "plot_leakage_profile",
    "plot_edge_population_summary",
    "make_run_report",
    "PROGRESS_SCHEMA_VERSION",
    "ProgressEvent",
    "ProgressReporter",
    "NullReporter",
    "HistoryReporter",
    "JupyterLiveReporter",
    "history_to_dataframe",
    "plot_history",
    "GateSequence",
    "GateTimeParam",
    "PrimitiveGate",
    "DriftPhaseModel",
    "QubitRotation",
    "SQR",
    "CavityBlockPhase",
    "SNAP",
    "Displacement",
    "ConditionalDisplacement",
    "JaynesCummingsExchange",
    "BlueSidebandExchange",
    "FreeEvolveCondPhase",
    "make_gate_from_matrix",
    "make_gate_from_callable",
    "make_gate_from_waveform",
    "GateRegistry",
    "gate_registry",
    "GateOrderConfig",
    "GateOrderOptimizer",
    "GateOrderSearchResult",
    "drift_hamiltonian_qobj",
    "drift_phase_table",
    "drift_phase_from_hamiltonian",
    "drift_phase_unitary",
]