import warnings

from .backends import SimulationResult, simulate_sequence
from .config import ExecutionOptions, LeakagePenalty, MultiObjective, Normal, ParameterDistribution, SynthesisConstraints, Uniform
from .constraints import (
    TimeGridResult,
    SlewConstraintResult,
    ToneSpacingResult,
    enforce_slew_limit,
    evaluate_tone_spacing,
    piecewise_constant_samples,
    project_tone_frequencies,
    snap_times_to_grid,
)
from . import metrics
from .metrics import (
    channel_action_metrics,
    channel_average_gate_fidelity,
    channel_entanglement_fidelity,
    channel_process_fidelity,
    isometry_basis_fidelity,
    isometry_coherent_fidelity,
    isometry_random_superposition_metrics,
    isometry_retention,
    leakage_metrics,
    LogicalBlockPhaseDiagnostics,
    logical_block_phase_diagnostics,
    operator_truncation_sanity_metrics,
    projected_density_matrix,
    projector_population_metrics,
    state_population_distribution,
    subspace_unitary_process_fidelity,
    subspace_unitary_fidelity,
    truncation_sanity_metrics,
)
from .objectives import (
    MetricSpec,
    default_metric_specs,
    metric_cost,
    metric_sense,
    normalize_metric_name,
    objective_preset_defaults,
    resolve_metric_specs,
)
from .optim import ParetoFrontResult, SynthesisResult, TimeMapper
from .optim import UnitarySynthesizer as QuantumMapSynthesizer
from .progress import (
    PROGRESS_SCHEMA_VERSION,
    HistoryReporter,
    JupyterLiveReporter,
    NullReporter,
    ProgressEvent,
    ProgressReporter,
    history_to_dataframe,
    plot_history,
)
from .reporting import make_run_report
from .sequence import (
    BlueSidebandExchange,
    CavityBlockPhase,
    ConditionalDisplacement,
    Displacement,
    DriftPhaseModel,
    FreeEvolveCondPhase,
    GateTimeParam,
    GateSequence,
    JaynesCummingsExchange,
    PrimitiveGate,
    QubitRotation,
    SNAP,
    SQR,
    drift_hamiltonian_qobj,
    drift_phase_table,
    drift_phase_from_hamiltonian,
    drift_phase_unitary,
    make_gate_from_matrix,
    make_gate_from_callable,
    make_gate_from_waveform,
)
from .subspace import Subspace
from .systems import CQEDSystemAdapter, GateRegistry, QuantumSystem, gate_registry
from .targets import (
    ObservableTarget,
    SubspaceSpec,
    TargetChannel,
    TargetIsometry,
    TargetReducedStateMapping,
    TargetStateMapping,
    TargetUnitary,
    TrajectoryCheckpoint,
    TrajectoryTarget,
    coerce_target,
    make_target,
)
from .visualization import (
    plot_density_matrix_heatmap,
    plot_edge_population_summary,
    plot_leakage_block_heatmap,
    plot_leakage_profile,
    plot_operator_magnitude_heatmap,
    plot_output_population_bars,
    plot_projected_logical_density,
    reorder_operator_by_subspace,
)
from .waveform_bridge import waveform_primitive_from_gate, waveform_sequence_from_gates
from .order_search import GateOrderConfig, GateOrderOptimizer, GateOrderSearchResult


_LEGACY_SYNTH_WARNING_EMITTED = False


class UnitarySynthesizer(QuantumMapSynthesizer):
    def __init__(self, *args, **kwargs):
        global _LEGACY_SYNTH_WARNING_EMITTED
        if not _LEGACY_SYNTH_WARNING_EMITTED:
            warnings.warn(
                "UnitarySynthesizer from cqed_sim.unitary_synthesis is deprecated and will be removed in a future release; use cqed_sim.map_synthesis.QuantumMapSynthesizer instead.",
                FutureWarning,
                stacklevel=1,
            )
            _LEGACY_SYNTH_WARNING_EMITTED = True
        super().__init__(*args, **kwargs)

__all__ = [
    "Subspace",
    "QuantumSystem",
    "CQEDSystemAdapter",
    "SubspaceSpec",
    "make_target",
    "coerce_target",
    "TargetUnitary",
    "TargetStateMapping",
    "TargetReducedStateMapping",
    "TargetIsometry",
    "TargetChannel",
    "ObservableTarget",
    "TrajectoryCheckpoint",
    "TrajectoryTarget",
    "waveform_primitive_from_gate",
    "waveform_sequence_from_gates",
    "TimeMapper",
    "SynthesisResult",
    "ParetoFrontResult",
    "UnitarySynthesizer",
    "QuantumMapSynthesizer",
    "SynthesisConstraints",
    "LeakagePenalty",
    "MultiObjective",
    "ExecutionOptions",
    "Normal",
    "Uniform",
    "ParameterDistribution",
    "MetricSpec",
    "default_metric_specs",
    "metric_cost",
    "metric_sense",
    "normalize_metric_name",
    "objective_preset_defaults",
    "resolve_metric_specs",
    "TimeGridResult",
    "SlewConstraintResult",
    "ToneSpacingResult",
    "SimulationResult",
    "simulate_sequence",
    "snap_times_to_grid",
    "piecewise_constant_samples",
    "enforce_slew_limit",
    "evaluate_tone_spacing",
    "project_tone_frequencies",
    "metrics",
    "subspace_unitary_fidelity",
    "subspace_unitary_process_fidelity",
    "leakage_metrics",
    "channel_action_metrics",
    "projector_population_metrics",
    "projected_density_matrix",
    "state_population_distribution",
    "channel_process_fidelity",
    "channel_entanglement_fidelity",
    "channel_average_gate_fidelity",
    "isometry_coherent_fidelity",
    "isometry_basis_fidelity",
    "isometry_retention",
    "isometry_random_superposition_metrics",
    "LogicalBlockPhaseDiagnostics",
    "logical_block_phase_diagnostics",
    "truncation_sanity_metrics",
    "operator_truncation_sanity_metrics",
    "reorder_operator_by_subspace",
    "plot_operator_magnitude_heatmap",
    "plot_leakage_block_heatmap",
    "plot_output_population_bars",
    "plot_density_matrix_heatmap",
    "plot_projected_logical_density",
    "plot_leakage_profile",
    "plot_edge_population_summary",
    "make_run_report",
    "PROGRESS_SCHEMA_VERSION",
    "ProgressEvent",
    "ProgressReporter",
    "NullReporter",
    "HistoryReporter",
    "JupyterLiveReporter",
    "history_to_dataframe",
    "plot_history",
    "GateSequence",
    "GateTimeParam",
    "PrimitiveGate",
    "DriftPhaseModel",
    "QubitRotation",
    "SQR",
    "CavityBlockPhase",
    "SNAP",
    "Displacement",
    "ConditionalDisplacement",
    "JaynesCummingsExchange",
    "BlueSidebandExchange",
    "FreeEvolveCondPhase",
    "make_gate_from_matrix",
    "make_gate_from_callable",
    "make_gate_from_waveform",
    "GateRegistry",
    "gate_registry",
    "GateOrderConfig",
    "GateOrderOptimizer",
    "GateOrderSearchResult",
    "drift_hamiltonian_qobj",
    "drift_phase_table",
    "drift_phase_from_hamiltonian",
    "drift_phase_unitary",
]
